version: '3.8'
services:
  app:
    image: nginx:1.24.0
    ports:
      - "8080:80"
    environment:
      NODE_ENV: "production"
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: postgres:15.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    image: redis:7.0.10-alpine
    command: redis-server --requirepass "redispass123"
    ports:
      - "6379:6379"

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge